### ISSUE TITLE
🔴 Kanaban Board

### ISSUE THREAD

**Issue by NatanimA** [NatanimA/space-travellers-react-capstone#31]
Student A - Natanim Abesha
Student B - Kolapo Akinrinlola
**Please Note that Dragons page section is not required since we are two**
Links to the Kanaban board - https://github.com/users/NatanimA/projects/4/views/1

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @NatanimA and @LIBERCOSOFT,

Good job so far!
✔️ Kanban columns are well created
✔️ Tasks are assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly distribute your tasks evenly. I can see @NatanimA has about 11 tasks, whereas @LIBERCOSOFT has only 6. Kindly share your tasks fairly

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
